project:
  type: website
  output-dir: docs

website:
  title: "Duration of response in oncology"
  navbar:
    left:
    - href: index.qmd
      text: Main
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

