---
title: "Appendix"
format: 
  html:
    html-math-method: katex
    toc: true
    toc-depth: 4
    toc-expand: true
execute: 
  # eval: false
  echo: true
  cache: true
bibliography: references.bib
---

This appendix contains technical details of the DOR methodology outlined in [Main](index.qmd).

### Asymptotic distribution of $\hat S_D(t)$

Using the functional delta method on the estimator $\hat{G}_C(t)$ within 
$\hat S_D(t)$, we can show that, as $n\to\infty$, 
$\hat S_{D}(t)\to_p S_D(t)$ and 
$n^{1/2}\{\hat{S}_{D}(t)-S_D(t)\}\to_d N\{0,\sigma^2_{D}(t)\}$, with $\sigma^2_{D}(t)$ consistently
estimated by
$$\hat\sigma^2_{D}(t)=n^{-1}\sum_{i=1}^n\left\{
\frac{\Delta_{2i}}{\hat G_C(X_{2i})}I(\tilde D_i>t)-\hat S_{D}(t)
+\int_0^\tau \frac{\hat\zeta(u,t)}{\hat\pi_2(u)}{\rm d}\hat M_i^C(u)
\right\}^2,$$
where $\hat\zeta(u,t)=
n^{-1}\sum_{i=1}^n\Delta_{2i}I(\tilde D_i>t,X_{2i}\geq u)/\hat G_C(X_{2i})$,
$\hat\pi_2(u)=n^{-1}\sum_{i=1}^nI(X_{2i}\geq u)$,
$\hat M_i^C(u)=I(X_{2i}\leq u, \Delta_{2i}=0)-\hat\Lambda_C(X_{2i}\wedge u)$,
and $\hat\Lambda_C(\cdot)$ is the Nelsen-Aalen estimator
for the cumulative hazard function of $C$.

### Inference on the median

Let $\mathcal M(S_D)=\inf\{t: S_D(t)\leq 0.5\}$ denote the median operator
on the survival function $S_D(\cdot)$. Then the estimator for median DOR
is just $\mathcal M(\hat S_D)$. To make inference, we need to quantify the randomness
in $\hat S_D(t)$ as a Gaussian process. To do so, note that the previous section
suggests that the influence function of $\hat S_D(t)$ is estimated by

$$
\hat\eta_i(t)\equiv \frac{\Delta_{2i}}{\hat G_C(X_{2i})}I(\tilde D_i>t)-\hat S_{D}(t)
+\int_0^\tau \frac{\hat\zeta(u,t)}{\hat\pi_2(u)}{\rm d}\hat M_i^C(u).
$$
This means that the asymptotic distribution of $\hat S_D(t)$ is approximated by
the Gaussian process 

$$
\underbrace{S_D(t)}_{\rm central\, term} + 
\underbrace{n^{-1}\hat{\boldsymbol\eta}(t)^{\rm T}\boldsymbol Z}_{\rm perturbation\, term}, 
$$
where ${\boldsymbol\eta}(t) = \{\hat\eta_1(t),\ldots, \hat\eta_n(t)\}^{\rm T}$
and $\boldsymbol Z = (Z_1, \ldots, Z_n)^{\rm T}$ is a vector of i.i.d. standard normal
random variables. Then we can approximate the asymptotic distribution of 
$\mathcal M(\hat S_D)$ by that of $\mathcal M\left\{\hat S_D(\cdot) + n^{-1}\hat{\boldsymbol\eta}(\cdot)^{\rm T}\boldsymbol Z\right\}$ under repeatedly generated $\boldsymbol Z$
(the default is $N = 1000$ replicates).



